'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import Image from 'next/image';

// Color Palette
const COLORS = {
  bg: '#0c1225',
  surface: '#111a32',
  border: 'rgba(107, 155, 209, 0.15)',
  text: '#e2e8f0',
  textMuted: '#8899b4',
  textFaint: '#4a5f80',
  primary: '#ff6b35',
  primaryGlow: 'rgba(255, 107, 53, 0.15)',
  blueLight: '#6b9bd1',
};

export function StoryBasedMonitoringSimple() {
  const [windowWidth, setWindowWidth] = useState(1024);

  useEffect(() => {
    setWindowWidth(window.innerWidth);
    const handleResize = () => setWindowWidth(window.innerWidth);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  const isMobile = windowWidth < 768;

  return (
    <div style={{ background: COLORS.bg, minHeight: '100vh' }}>
      {/* Hero */}
      <section
        style={{
          minHeight: '100vh',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: 'clamp(6rem, 20vw, 9rem) 1.5rem 4rem',
          background: `radial-gradient(ellipse 80% 60% at 50% 40%, ${COLORS.primaryGlow} 0%, transparent 60%), ${COLORS.bg}`,
        }}
      >
        <div style={{ maxWidth: '900px', textAlign: 'center' }}>
          <p
            style={{
              fontSize: isMobile ? '14px' : '16px',
              fontWeight: '800',
              color: COLORS.primary,
              fontFamily: 'Inter, sans-serif',
              letterSpacing: '0.1em',
              textTransform: 'uppercase',
              marginBottom: '1.5rem',
            }}
          >
            Story-based Monitoring
          </p>
          <h1
            style={{
              fontFamily: 'var(--font-space-grotesk, "Space Grotesk", sans-serif)',
              fontSize: isMobile ? '2.5rem' : '4rem',
              fontWeight: 700,
              lineHeight: 1.1,
              letterSpacing: '-0.03em',
              color: COLORS.text,
              marginBottom: '2rem',
            }}
          >
            AI Agents Are Shipping Code.
            <br />
            <span style={{ color: COLORS.primary }}>Make sure they did what you intended.</span>
          </h1>
          <p
            style={{
              fontSize: isMobile ? '1.125rem' : '1.375rem',
              lineHeight: 1.6,
              color: COLORS.textMuted,
              maxWidth: '720px',
              margin: '0 auto',
            }}
          >
            Tests check syntax. Monitoring checks status codes. Neither catches when your AI agent ships a payment flow without the fraud check.
          </p>
        </div>
      </section>

      {/* The Product */}
      <section
        style={{
          padding: isMobile ? '4rem 1.5rem' : '6rem 2rem',
          background: COLORS.bg,
        }}
      >
        <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
          <div
            style={{
              background: COLORS.surface,
              borderRadius: '16px',
              padding: isMobile ? '2rem' : '3rem',
              border: `1px solid ${COLORS.border}`,
              marginBottom: '3rem',
            }}
          >
            {/* Screenshot */}
            <div
              style={{
                position: 'relative',
                borderRadius: '8px',
                marginBottom: '2rem',
                overflow: 'hidden',
                border: `1px solid ${COLORS.border}`,
              }}
            >
              <Image
                src="/otel1_manifest_screenshot.png"
                alt="OTEL Behavioral Manifest - Auto-generated workflow templates"
                width={1200}
                height={800}
                style={{
                  width: '100%',
                  height: 'auto',
                  display: 'block',
                }}
              />
              <div
                style={{
                  position: 'absolute',
                  bottom: '1rem',
                  right: '1rem',
                  background: 'rgba(0, 0, 0, 0.85)',
                  padding: '0.75rem 1rem',
                  borderRadius: '6px',
                  border: `1px solid ${COLORS.primary}`,
                }}
              >
                <div
                  style={{
                    fontSize: '13px',
                    color: COLORS.primary,
                    fontFamily: 'Inter, sans-serif',
                    fontWeight: 500,
                  }}
                >
                  ← Auto-generated by AI agent from codebase.
                  <br />
                  Validates runtime behavior. Zero manual work.
                </div>
              </div>
            </div>

            <p
              style={{
                fontSize: isMobile ? '15px' : '17px',
                lineHeight: 1.7,
                color: COLORS.textMuted,
                textAlign: 'center',
                maxWidth: '680px',
                margin: '0 auto',
              }}
            >
              Principal&apos;s AI agent reads your codebase, generates behavioral templates, and validates runtime OTEL spans. You review for coverage. The verification happens automatically.
            </p>
          </div>

          {/* How It Works */}
          <div style={{ textAlign: 'center', marginBottom: '4rem' }}>
            <h2
              style={{
                fontFamily: 'var(--font-space-grotesk, "Space Grotesk", sans-serif)',
                fontSize: isMobile ? '2rem' : '3rem',
                fontWeight: 700,
                color: COLORS.text,
                marginBottom: '3rem',
              }}
            >
              How It Works
            </h2>

            <div
              style={{
                display: 'grid',
                gridTemplateColumns: isMobile ? '1fr' : 'repeat(3, 1fr)',
                gap: '2rem',
                maxWidth: '960px',
                margin: '0 auto',
              }}
            >
              {[
                {
                  number: '01',
                  title: 'Agent reads your code',
                  description: 'Point Principal agent at your codebase. It maps workflows, understands structure, identifies expected behavior.',
                },
                {
                  number: '02',
                  title: 'Generates templates',
                  description: 'Auto-creates behavioral templates with {{variables}}. Decision {{decisionId}} created with title "{{title}}".',
                },
                {
                  number: '03',
                  title: 'Validates at runtime',
                  description: 'OTEL spans fill the blanks. If Decision Create does not create a decision, the template breaks. That is how you know.',
                },
              ].map((step) => (
                <div
                  key={step.number}
                  style={{
                    padding: '2rem',
                    background: COLORS.surface,
                    border: `1px solid ${COLORS.border}`,
                    borderRadius: '12px',
                    textAlign: 'left',
                  }}
                >
                  <div
                    style={{
                      fontFamily: 'monospace',
                      fontSize: '12px',
                      color: COLORS.primary,
                      fontWeight: 600,
                      marginBottom: '1rem',
                    }}
                  >
                    {step.number}
                  </div>
                  <h3
                    style={{
                      fontFamily: 'var(--font-space-grotesk, "Space Grotesk", sans-serif)',
                      fontSize: '1.25rem',
                      fontWeight: 600,
                      color: COLORS.text,
                      marginBottom: '0.75rem',
                    }}
                  >
                    {step.title}
                  </h3>
                  <p
                    style={{
                      fontSize: '15px',
                      lineHeight: 1.6,
                      color: COLORS.textMuted,
                      margin: 0,
                    }}
                  >
                    {step.description}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Why Now - AI Agents Need Behavioral Guardrails */}
          <div style={{ textAlign: 'center', marginBottom: '4rem' }}>
            <h2
              style={{
                fontFamily: 'var(--font-space-grotesk, "Space Grotesk", sans-serif)',
                fontSize: isMobile ? '2rem' : '3.5rem',
                fontWeight: 700,
                lineHeight: 1.2,
                marginBottom: '1rem',
              }}
            >
              <div style={{ color: COLORS.text }}>AI Agents Need</div>
              <div style={{ color: COLORS.primary }}>Behavioral Guardrails</div>
            </h2>
            <p
              style={{
                fontSize: isMobile ? '15px' : '17px',
                lineHeight: 1.7,
                color: COLORS.textMuted,
                maxWidth: '800px',
                margin: '0 auto 3rem',
              }}
            >
              Agents do not just write code - they ship it. They make autonomous decisions.
              And they can succeed at every step while completely missing the point.
              Traditional monitoring was not built for this.
            </p>

            <div
              style={{
                display: 'grid',
                gridTemplateColumns: isMobile ? '1fr' : 'repeat(2, 1fr)',
                gap: '1.5rem',
                maxWidth: '1000px',
                margin: '0 auto',
              }}
            >
              {[
                {
                  icon: '⚠',
                  title: 'Silent failures are the new norm',
                  description: 'An agent can complete every operation successfully and still violate the requirement. Status codes will not catch it.',
                },
                {
                  icon: '📋',
                  title: 'You need ground truth',
                  description: 'The manifest becomes the source of "should" in your system. Not documentation. Not tribal knowledge. A versioned, durable artifact.',
                },
                {
                  icon: '✓',
                  title: 'Verification happens at runtime',
                  description: 'The storyboard does not just show what happened - it shows whether it matched the declared intent. Instantly.',
                },
                {
                  icon: '🌐',
                  title: 'It\'s still OpenTelemetry',
                  description: 'No proprietary formats. No vendor lock-in. Standard OTEL spans, enriched with behavioral verification. Use your existing instrumentation.',
                },
              ].map((item, i) => (
                <div
                  key={i}
                  style={{
                    background: COLORS.surface,
                    border: `1px solid ${COLORS.border}`,
                    borderRadius: '12px',
                    padding: isMobile ? '1.5rem' : '2rem',
                    textAlign: 'left',
                  }}
                >
                  <h3
                    style={{
                      fontFamily: 'var(--font-space-grotesk, "Space Grotesk", sans-serif)',
                      fontSize: isMobile ? '1.125rem' : '1.25rem',
                      fontWeight: 700,
                      color: COLORS.text,
                      marginBottom: '0.75rem',
                    }}
                  >
                    {item.title}
                  </h3>
                  <p
                    style={{
                      fontSize: '15px',
                      lineHeight: 1.6,
                      color: COLORS.textMuted,
                      margin: 0,
                    }}
                  >
                    {item.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section
        style={{
          padding: isMobile ? '4rem 1.5rem' : '6rem 2rem',
          background: `radial-gradient(ellipse 80% 50% at 50% 50%, ${COLORS.primaryGlow} 0%, transparent 60%), ${COLORS.bg}`,
        }}
      >
        <div style={{ maxWidth: '720px', margin: '0 auto', textAlign: 'center' }}>
          <h2
            style={{
              fontFamily: 'var(--font-space-grotesk, "Space Grotesk", sans-serif)',
              fontSize: isMobile ? '2rem' : '3rem',
              fontWeight: 700,
              color: COLORS.text,
              marginBottom: '1.5rem',
            }}
          >
            Try the Interactive Demo
          </h2>
          <p
            style={{
              fontSize: '1.125rem',
              lineHeight: 1.6,
              color: COLORS.textMuted,
              marginBottom: '2.5rem',
            }}
          >
            Explore a real working example using Backlog.md - an open-source task manager. See how manifests validate behavior, catch silent failures, and generate storyboards in real-time.
          </p>

          <Link
            href="/observability-demo"
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              justifyContent: 'center',
              padding: '1rem 2.5rem',
              borderRadius: '999px',
              fontFamily: 'var(--font-inter, Inter, sans-serif)',
              fontSize: '1rem',
              fontWeight: 600,
              textDecoration: 'none',
              background: COLORS.primary,
              color: '#fff',
              transition: 'transform 0.2s ease, box-shadow 0.2s ease',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.transform = 'translateY(-2px)';
              e.currentTarget.style.boxShadow = '0 8px 24px rgba(255, 107, 53, 0.35)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.transform = 'translateY(0)';
              e.currentTarget.style.boxShadow = 'none';
            }}
          >
            Launch Interactive Demo →
          </Link>

          <p
            style={{
              fontSize: '14px',
              color: COLORS.textFaint,
              fontStyle: 'italic',
              marginTop: '1.5rem',
            }}
          >
            No signup required. Fully interactive in your browser.
          </p>
        </div>
      </section>
    </div>
  );
}
